# Generated by Django 4.0.3 on 2022-03-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.FileField(default='default.png', upload_to='images/'),
        ),
    ]
